language: r
sudo: require
cran: https://cran.rstudio.com/


# System dependencies
before_install:
 - sudo apt-get install libvtk5-dev
 - sudo apt-get install python-dev
 - sudo apt-get install python-vtk
 - sudo apt-get install libssh2-1-dev
 - sudo apt-get install libhdf5-7
 - sudo apt-get install libhdf5-dev
 - sudo apt-get install libcurl4-openssl-dev
 - sudo apt-get install libxml2-dev
 - sudo apt-get install bison 
 - sudo apt-get install flex 
 - sudo apt-get install freeglut3 
 - sudo apt-get install freeglut3-dev 
 - sudo apt-get install libxi6 
 - sudo apt-get install libxi-dev 
 - sudo apt-get install libxmu6 
 - sudo apt-get install libxmu-dev 
 - sudo apt-get install libxmu-headers

#Git Binary installs
r_binary_install:
  - lme4

r_github_packages:
  - hadley/dplyr
  - hadley/ggplot2

# Source/R installs
install:
  - Rscript -e "print(R.version)"
  - sudo bash install_netcdf4.sh
  - sudo bash install_minctoolkit.sh
  - Rscript r_package_install.Rscript