language: r
sudo: require
cran: http://cran.rstudio.com/

# System dependencies
before_install:
 # remove cran's apt repository to install hdf5
 - sudo add-apt-repository -ry "deb http://cran.rstudio.com//bin/linux/ubuntu $(lsb_release -cs)/"
 - sudo add-apt-repository -ry "ppa:marutter/c2d4u"
 - sudo apt-get update -qq
 
 - sudo apt-get install -y libvtk5-dev
 - sudo apt-get install -y python-dev
 - sudo apt-get install -y python-vtk
 - sudo apt-get install -y libssh2-1-dev
 - sudo apt-get install -y libcurl4-openssl-dev
 - sudo apt-get install -y libhdf5-serial-dev
 
 # Add it back for downstream stuff 
 - sudo add-apt-repository -y "deb http://cran.rstudio.com//bin/linux/ubuntu $(lsb_release -cs)/"
 - sudo add-apt-repository -y "ppa:marutter/c2d4u"
 - sudo apt-get update -qq

#Git Binary installs
r_binary_install:
  - lme4

r_github_packages:
  - hadley/dplyr
  - hadley/ggplot2

# Source/R installs
install:
  - sudo bash install_libminc.sh
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  - Rscript r_package_install.Rscript