language: r
sudo: require
cran: https://cran.rstudio.com/
r_build_args: --no-multiarch --with-keep.source --configure-args="--with-build-path=$RMINC_BUILD_PATH"

# System dependencies
before_install:
 - sudo apt-get install -y libvtk5-dev
 - sudo apt-get install -y python-dev
 - sudo apt-get install -y python-vtk
 - sudo apt-get install -y libssh2-1-dev
 - sudo apt-get install -y libcurl4-openssl-dev
 - sudo bash dpkg_get_selections_script.sh
 - sudo apt-get install -y libhdf5-serial-dev

#Git Binary installs
r_binary_install:
  - lme4

r_github_packages:
  - hadley/dplyr
  - hadley/ggplot2

# Source/R installs
install:
  - sudo bash install_libminc.sh
  - Rscript r_package_install.Rscript