language: r
sudo: require
cran: http://cran.rstudio.com/
r_build_args: --no-multiarch --with-keep.source --configure-args="--with-build-path=$RMINC_BUILD_PATH"

addons:
  apt:
      sources:
          - ubuntu-toolchain-r-test
	  - llvm-toolchain-precise
	  - llvm-toolchain-precise-3.6

# System dependencies
before_install:
# - sudo apt-get install -y aptitude
 - sudo apt-get install -y libvtk5-dev
 - sudo apt-get install -y python-dev
 - sudo apt-get install -y python-vtk
 - sudo apt-get install -y libssh2-1-dev
 - sudo apt-get install -y libcurl4-openssl-dev
 - sudo aptitude install -y libhdf5-serial-dev



#Git Binary installs
r_binary_install:
  - lme4

r_github_packages:
  - hadley/dplyr
  - hadley/ggplot2

# Source/R installs
install:
  - sudo bash install_libminc.sh
  - Rscript r_package_install.Rscript